-- Crear la tabla de tasas de cambio
CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binance_rate DECIMAL(10,2) NOT NULL,
    eldorado_rate DECIMAL(10,2) NOT NULL,
    syklo_rate DECIMAL(10,2) NOT NULL,
    yadio_rate DECIMAL(10,2) NOT NULL,
    total_rate DECIMAL(10,2) NOT NULL,
    datetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Índices para mejorar el rendimiento de las consultas
    CONSTRAINT valid_rates CHECK (
        binance_rate >= 0 AND
        eldorado_rate >= 0 AND
        syklo_rate >= 0 AND
        yadio_rate >= 0 AND
        total_rate >= 0
    )
);

-- Crear índice para búsquedas por fecha
CREATE INDEX idx_exchange_rates_datetime ON exchange_rates(datetime);

-- Comentarios de la tabla
COMMENT ON TABLE exchange_rates IS 'Tabla que almacena las tasas de cambio de diferentes plataformas';
COMMENT ON COLUMN exchange_rates.binance_rate IS 'Tasa de cambio de Binance';
COMMENT ON COLUMN exchange_rates.eldorado_rate IS 'Tasa de cambio de Eldorado';
COMMENT ON COLUMN exchange_rates.syklo_rate IS 'Tasa de cambio de Syklo';
COMMENT ON COLUMN exchange_rates.yadio_rate IS 'Tasa de cambio de Yadio';
COMMENT ON COLUMN exchange_rates.total_rate IS 'Promedio de todas las tasas';
COMMENT ON COLUMN exchange_rates.datetime IS 'Fecha y hora de registro de las tasas';
