-- Crear la tabla de tasas de cambio
CREATE TABLE monitor_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airtm_rate DECIMAL(10,2) NOT NULL,
    billeterap2p_rate DECIMAL(10,2) NOT NULL,
    cambiosrya_rate DECIMAL(10,2) NOT NULL,
    eldorado_rate DECIMAL(10,2) NOT NULL,
    mkfrontera_rate DECIMAL(10,2) NOT NULL,
    syklo_rate DECIMAL(10,2) NOT NULL,
    usdtbnbvzla_rate DECIMAL(10,2) NOT NULL,
    yadio_rate DECIMAL(10,2) NOT NULL,
    total_rate DECIMAL(10,2) NOT NULL,
    datetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Índices para mejorar el rendimiento de las consultas
    CONSTRAINT valid_rates CHECK (
        airtm_rate > 0 AND
        billeterap2p_rate > 0 AND
        cambiosrya_rate > 0 AND
        eldorado_rate > 0 AND
        mkfrontera_rate > 0 AND
        syklo_rate > 0 AND
        usdtbnbvzla_rate > 0 AND
        yadio_rate > 0 AND
        total_rate > 0
    )
);

-- Crear índice para búsquedas por fecha
CREATE INDEX idx_monitor_rates_datetime ON monitor_rates(datetime);
CREATE INDEX idx_monitor_rates_created_at ON monitor_rates(created_at);

